"""
AI-Generated Templates System Models

This module handles AI-generated templates that are created on-demand based on user interests.
Templates start as 'pending', can be reviewed/edited by staff, and become 'approved' for reuse.
"""

from sqlalchemy import (
    Column, Integer, String, Text, DateTime, Boolean, ForeignKey, Float, ARRAY
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import text

from app.models.base import Base, TimestampMixin


class AIGeneratedTemplate(Base, TimestampMixin):
    """
    AI-generated templates created on-demand based on user interests.
    
    Workflow:
    1. User enters interests when creating group
    2. Claude generates 10 custom templates
    3. Templates saved with status='pending'
    4. Staff reviews in dashboard (adopt/edit/reject)
    5. Approved templates become available for others with similar interests
    """
    __tablename__ = 'ai_generated_templates'
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    slug = Column(String, nullable=False, unique=True, index=True)
    description = Column(Text, nullable=True)
    category = Column(String, nullable=True)  # auto-categorized by AI
    icon = Column(String, nullable=True)  # emoji suggested by AI
    
    # What interests triggered this template?
    source_interests = Column(ARRAY(String), nullable=False, index=True)
    
    # AI generation metadata
    ai_model = Column(String, nullable=False, default='claude-3.5-sonnet')
    ai_prompt_used = Column(Text, nullable=True)  # the prompt sent to Claude
    generation_timestamp = Column(DateTime(timezone=True), server_default=text('now()'), nullable=False)
    
    # Template structure (generated by AI)
    # Format: [{"title": "...", "description": "...", "order_index": 1, "ai_prompts": [...], "children": [...]}]
    sections = Column(JSONB, nullable=False)
    
    # Review status
    status = Column(String, nullable=False, default='pending', index=True)  # pending, approved, rejected, edited
    reviewed_by = Column(Integer, ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
    review_notes = Column(Text, nullable=True)
    
    # If staff edited the template (Kit's improved version)
    edited_sections = Column(JSONB, nullable=True)
    
    # Usage tracking
    times_suggested = Column(Integer, nullable=False, default=0)  # how many times AI suggested it
    times_selected = Column(Integer, nullable=False, default=0)  # how many times users picked it
    groups_using = Column(Integer, nullable=False, default=0)  # how many groups used it
    
    # Which group requested this template generation?
    requested_by_group = Column(Integer, ForeignKey('groups.id', ondelete='SET NULL'), nullable=True)
    
    # If approved, link to the canonical project_template
    approved_template_id = Column(Integer, ForeignKey('project_templates.id', ondelete='SET NULL'), nullable=True)
    
    # Relationships
    reviewer = relationship("User", foreign_keys=[reviewed_by])
    group = relationship("Group", foreign_keys=[requested_by_group])
    approved_template = relationship("ProjectTemplate", foreign_keys=[approved_template_id])


class TemplateInterestMapping(Base):
    """
    Many-to-many mapping between approved templates and interests.
    Allows smart template recommendations based on user interests.
    """
    __tablename__ = 'template_interest_mappings'
    
    id = Column(Integer, primary_key=True, index=True)
    template_id = Column(Integer, ForeignKey('project_templates.id', ondelete='CASCADE'), nullable=False)
    interest = Column(String, nullable=False, index=True)
    relevance_score = Column(Float, nullable=True, default=1.0)  # how relevant is this template to this interest?
    created_at = Column(DateTime(timezone=True), server_default=text('now()'), nullable=False)
    
    # Relationships
    template = relationship("ProjectTemplate", back_populates="interest_mappings")


class AIGenerationLog(Base):
    """
    Logs every AI template generation request for debugging and improvement.
    """
    __tablename__ = 'ai_generation_logs'
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    group_id = Column(Integer, ForeignKey('groups.id', ondelete='SET NULL'), nullable=True)
    interests = Column(ARRAY(String), nullable=False)
    
    # AI interaction details
    ai_model = Column(String, nullable=False)
    prompt_sent = Column(Text, nullable=False)
    response_received = Column(Text, nullable=True)
    templates_generated = Column(Integer, nullable=False, default=0)
    generation_time_ms = Column(Integer, nullable=True)  # how long did Claude take?
    
    # Error tracking
    error_message = Column(Text, nullable=True)
    success = Column(Boolean, nullable=False, default=True)
    
    created_at = Column(DateTime(timezone=True), server_default=text('now()'), nullable=False, index=True)
    
    # Relationships
    user = relationship("User")
    group = relationship("Group")
