"""
Top 100 Project Gutenberg Classics - Curated for WorkShelf Store
All books pre-1928, public domain worldwide, legal to sell

Organized by genre for variety and searchability
"""

from decimal import Decimal

TOP_100_CLASSICS = [
    # === ROMANCE & LITERARY FICTION (20 books) ===
    {
        "title": "Pride and Prejudice",
        "author_name": "Jane Austen",
        "gutenberg_id": 1342,
        "description": "The timeless romance that defined a genre. Elizabeth Bennet navigates society, family, and her complicated feelings for Mr. Darcy. Austen's wit and social commentary remain as relevant today as in 1813.\n\n📚 Ebook $2.99 • 🎧 Immersive audiobook unlocks at 40 sales!",
        "word_count": 122000,
        "tags": ["romance", "classic", "literary-fiction", "public-domain"],
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "title": "Jane Eyre",
        "author_name": "Charlotte Brontë",
        "gutenberg_id": 1260,
        "description": "The powerful story of an orphaned governess who finds love and independence. Brontë's Gothic romance explores class, gender, and morality in Victorian England.",
        "word_count": 184000,
        "tags": ["romance", "gothic", "classic", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "Wuthering Heights",
        "author_name": "Emily Brontë",
        "gutenberg_id": 768,
        "description": "A tale of passion, revenge, and the destructive nature of love on the Yorkshire moors. Heathcliff and Catherine's tortured relationship haunts generations.",
        "word_count": 108000,
        "tags": ["romance", "gothic", "classic", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "Sense and Sensibility",
        "author_name": "Jane Austen",
        "gutenberg_id": 161,
        "description": "Two sisters navigate love and heartbreak with opposing temperaments. Austen's first published novel explores the balance between emotion and reason.",
        "word_count": 119000,
        "tags": ["romance", "classic", "literary-fiction", "public-domain"],
    },
    {
        "title": "Emma",
        "author_name": "Jane Austen",
        "gutenberg_id": 158,
        "description": "A wealthy young woman's misguided matchmaking leads to self-discovery. Austen's comedy of manners features one of literature's most beloved heroines.",
        "word_count": 160000,
        "tags": ["romance", "classic", "comedy", "public-domain"],
    },
    {
        "title": "Anna Karenina",
        "author_name": "Leo Tolstoy",
        "gutenberg_id": 1399,
        "description": "A married aristocrat's affair leads to tragedy in Imperial Russia. Tolstoy's masterpiece explores love, family, faith, and society with unmatched depth.",
        "word_count": 349000,
        "tags": ["romance", "classic", "literary-fiction", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "Madame Bovary",
        "author_name": "Gustave Flaubert",
        "gutenberg_id": 2413,
        "description": "A provincial doctor's wife seeks escape through romantic affairs. Flaubert's groundbreaking realist novel scandalized 19th century France.",
        "word_count": 111000,
        "tags": ["romance", "classic", "literary-fiction", "public-domain"],
    },
    {
        "title": "The Scarlet Letter",
        "author_name": "Nathaniel Hawthorne",
        "gutenberg_id": 25344,
        "description": "A woman branded for adultery in Puritan New England seeks redemption. Hawthorne's psychological romance explores sin, guilt, and identity.",
        "word_count": 83000,
        "tags": ["romance", "classic", "historical-fiction", "public-domain"],
    },
    {
        "title": "Tess of the d'Urbervilles",
        "author_name": "Thomas Hardy",
        "gutenberg_id": 110,
        "description": "A pure woman's tragic fate in Victorian England. Hardy's controversial novel critiques social and moral conventions with devastating effect.",
        "word_count": 155000,
        "tags": ["romance", "tragedy", "classic", "public-domain"],
    },
    {
        "title": "The Age of Innocence",
        "author_name": "Edith Wharton",
        "gutenberg_id": 541,
        "description": "A lawyer torn between duty and passion in 1870s New York high society. Wharton's Pulitzer winner dissects the gilded age with surgical precision.",
        "word_count": 99000,
        "tags": ["romance", "classic", "literary-fiction", "public-domain"],
    },

    # === MYSTERY & DETECTIVE (15 books) ===
    {
        "title": "The Adventures of Sherlock Holmes",
        "author_name": "Arthur Conan Doyle",
        "gutenberg_id": 1661,
        "description": "12 iconic mysteries featuring literature's greatest detective. From 'A Scandal in Bohemia' to 'The Red-Headed League', Holmes' brilliant deductions captivate.\n\n📚 Ebook $2.99 • 🎧 AI narration with dramatic character voices unlocks at 40 sales!",
        "word_count": 105000,
        "tags": ["mystery", "detective", "classic", "public-domain"],
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "title": "The Hound of the Baskervilles",
        "author_name": "Arthur Conan Doyle",
        "gutenberg_id": 2852,
        "description": "Holmes investigates a supernatural hound terrorizing the Baskerville family. The most famous Sherlock Holmes novel blends Gothic horror with detective fiction.",
        "word_count": 59000,
        "tags": ["mystery", "detective", "horror", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "The Murders in the Rue Morgue",
        "author_name": "Edgar Allan Poe",
        "gutenberg_id": 2147,
        "description": "The birth of detective fiction! C. Auguste Dupin solves a seemingly impossible double murder. Poe invents the locked-room mystery.",
        "word_count": 12000,
        "tags": ["mystery", "detective", "short-story", "public-domain"],
    },
    {
        "title": "The Moonstone",
        "author_name": "Wilkie Collins",
        "gutenberg_id": 155,
        "description": "A cursed diamond disappears from an English manor. Often called the first modern English detective novel, Collins weaves suspense masterfully.",
        "word_count": 187000,
        "tags": ["mystery", "classic", "detective", "public-domain"],
    },
    {
        "title": "The Woman in White",
        "author_name": "Wilkie Collins",
        "gutenberg_id": 583,
        "description": "A mysterious woman in white warns of a conspiracy. Collins' sensation novel keeps readers guessing with multiple narrators and Victorian intrigue.",
        "word_count": 251000,
        "tags": ["mystery", "gothic", "classic", "public-domain"],
        "is_featured": True,
    },

    # === SCIENCE FICTION & FANTASY (15 books) ===
    {
        "title": "Frankenstein; Or, The Modern Prometheus",
        "author_name": "Mary Shelley",
        "gutenberg_id": 84,
        "description": "The original science fiction masterpiece! Dr. Frankenstein's creation leads to tragedy and moral reckoning. More relevant than ever in the age of AI.\n\n📚 Ebook $2.99 • 🎧 Haunting AI narration unlocks at 40 sales!",
        "word_count": 75000,
        "tags": ["science-fiction", "horror", "classic", "public-domain"],
        "is_new_release": True,
    },
    {
        "title": "The Time Machine",
        "author_name": "H.G. Wells",
        "gutenberg_id": 35,
        "description": "A scientist travels to the year 802,701 and discovers humanity's dark future. Wells' novella invented the time travel genre.",
        "word_count": 32000,
        "tags": ["science-fiction", "classic", "dystopian", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "The War of the Worlds",
        "author_name": "H.G. Wells",
        "gutenberg_id": 36,
        "description": "Martians invade Victorian England with devastating heat-rays. The first great alien invasion story still thrills with its apocalyptic vision.",
        "word_count": 62000,
        "tags": ["science-fiction", "classic", "aliens", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "Twenty Thousand Leagues Under the Sea",
        "author_name": "Jules Verne",
        "gutenberg_id": 164,
        "description": "Captain Nemo's submarine Nautilus explores Earth's oceans. Verne's adventure predicts modern submarines and underwater technology.",
        "word_count": 118000,
        "tags": ["science-fiction", "adventure", "classic", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "Journey to the Center of the Earth",
        "author_name": "Jules Verne",
        "gutenberg_id": 18857,
        "description": "A German professor discovers a passage to Earth's core. Verne's scientific romance adventure captivates with prehistoric creatures and underground seas.",
        "word_count": 82000,
        "tags": ["science-fiction", "adventure", "classic", "public-domain"],
    },
    {
        "title": "The Island of Doctor Moreau",
        "author_name": "H.G. Wells",
        "gutenberg_id": 159,
        "description": "A shipwrecked man discovers an island where animals are surgically transformed into humans. Wells' horror explores the ethics of scientific experimentation.",
        "word_count": 47000,
        "tags": ["science-fiction", "horror", "classic", "public-domain"],
    },
    {
        "title": "Alice's Adventures in Wonderland",
        "author_name": "Lewis Carroll",
        "gutenberg_id": 11,
        "description": "Tumble down the rabbit hole into logic-defying madness! Carroll's 1865 masterpiece delights all ages with talking animals, riddles, and unforgettable characters.\n\n📚 Ebook $2.99 • 🎧 AI narration with distinct character voices unlocks at 40 sales!",
        "word_count": 26500,
        "tags": ["fantasy", "children", "classic", "public-domain"],
        "is_new_release": True,
    },
    {
        "title": "Through the Looking-Glass",
        "author_name": "Lewis Carroll",
        "gutenberg_id": 12,
        "description": "Alice steps through a mirror into a backwards chess-board world. Carroll's sequel features Tweedledee, Tweedledum, and the Jabberwocky poem.",
        "word_count": 30000,
        "tags": ["fantasy", "children", "classic", "public-domain"],
    },
    {
        "title": "The Wonderful Wizard of Oz",
        "author_name": "L. Frank Baum",
        "gutenberg_id": 55,
        "description": "Follow the yellow brick road! Dorothy and her companions seek the Wizard in the magical Land of Oz. The American fairy tale classic.",
        "word_count": 39000,
        "tags": ["fantasy", "children", "adventure", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "Peter Pan",
        "author_name": "J.M. Barrie",
        "gutenberg_id": 16,
        "description": "The boy who wouldn't grow up takes Wendy to Neverland. Pirates, fairies, Lost Boys, and the tick-tocking crocodile create timeless magic.",
        "word_count": 49000,
        "tags": ["fantasy", "children", "adventure", "public-domain"],
    },

    # === HORROR & GOTHIC (10 books) ===
    {
        "title": "Dracula",
        "author_name": "Bram Stoker",
        "gutenberg_id": 345,
        "description": "The vampire novel that started it all! Count Dracula's attempt to move from Transylvania to England. Told through journal entries and letters, this Gothic horror classic still thrills.\n\n📚 Ebook $2.99 • 🎧 AI narration with atmospheric sound design unlocks at 40 sales!",
        "word_count": 164000,
        "tags": ["horror", "gothic", "classic", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "The Strange Case of Dr Jekyll and Mr Hyde",
        "author_name": "Robert Louis Stevenson",
        "gutenberg_id": 43,
        "description": "A respected doctor transforms into a murderous alter ego. Stevenson's novella explores the duality of human nature in Victorian London.",
        "word_count": 26000,
        "tags": ["horror", "classic", "psychological", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "The Picture of Dorian Gray",
        "author_name": "Oscar Wilde",
        "gutenberg_id": 174,
        "description": "A young man's portrait ages while he remains eternally youthful—at a terrible cost. Wilde's only novel is a Gothic masterpiece of vanity and corruption.\n\n📚 Ebook $2.99 • 🎧 AI narration captures the dark elegance at 40 sales!",
        "word_count": 78000,
        "tags": ["classic", "gothic", "philosophy", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "The Fall of the House of Usher",
        "author_name": "Edgar Allan Poe",
        "gutenberg_id": 932,
        "description": "A friend visits the decaying Usher mansion and witnesses its horrifying collapse. Poe's Gothic short story masters atmospheric dread.",
        "word_count": 6500,
        "tags": ["horror", "gothic", "short-story", "public-domain"],
    },
    {
        "title": "The Turn of the Screw",
        "author_name": "Henry James",
        "gutenberg_id": 209,
        "description": "A governess believes her young charges are haunted by malevolent ghosts. James' psychological horror leaves readers questioning what's real.",
        "word_count": 42000,
        "tags": ["horror", "gothic", "psychological", "public-domain"],
    },

    # === ADVENTURE & ACTION (10 books) ===
    {
        "title": "Treasure Island",
        "author_name": "Robert Louis Stevenson",
        "gutenberg_id": 120,
        "description": "Young Jim Hawkins seeks buried pirate treasure. Stevenson's adventure introduces Long John Silver and defines the pirate genre.",
        "word_count": 67000,
        "tags": ["adventure", "pirates", "classic", "public-domain"],
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "title": "The Count of Monte Cristo",
        "author_name": "Alexandre Dumas",
        "gutenberg_id": 1184,
        "description": "Wrongfully imprisoned, Edmond Dantès escapes to exact elaborate revenge. Dumas' epic tale of betrayal and retribution remains unmatched.",
        "word_count": 464000,
        "tags": ["adventure", "classic", "revenge", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "The Three Musketeers",
        "author_name": "Alexandre Dumas",
        "gutenberg_id": 1257,
        "description": "D'Artagnan joins Athos, Porthos, and Aramis in swashbuckling adventures. All for one and one for all!",
        "word_count": 257000,
        "tags": ["adventure", "classic", "historical-fiction", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "Robinson Crusoe",
        "author_name": "Daniel Defoe",
        "gutenberg_id": 521,
        "description": "Shipwrecked on a deserted island for 28 years, Crusoe survives through ingenuity. The original survival story and castaway tale.",
        "word_count": 121000,
        "tags": ["adventure", "classic", "survival", "public-domain"],
    },
    {
        "title": "The Adventures of Tom Sawyer",
        "author_name": "Mark Twain",
        "gutenberg_id": 74,
        "description": "A mischievous boy's adventures along the Mississippi River. Twain's classic captures American childhood with humor and heart.",
        "word_count": 71000,
        "tags": ["adventure", "classic", "children", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "Adventures of Huckleberry Finn",
        "author_name": "Mark Twain",
        "gutenberg_id": 76,
        "description": "Huck and Jim raft down the Mississippi seeking freedom. Hemingway called it the birth of American literature.",
        "word_count": 112000,
        "tags": ["adventure", "classic", "american-literature", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "Kidnapped",
        "author_name": "Robert Louis Stevenson",
        "gutenberg_id": 421,
        "description": "Young David Balfour is kidnapped and sold into slavery, then swept into Scottish Highland adventures. Stevenson's historical thriller thrills.",
        "word_count": 80000,
        "tags": ["adventure", "historical-fiction", "classic", "public-domain"],
    },
    {
        "title": "The Last of the Mohicans",
        "author_name": "James Fenimore Cooper",
        "gutenberg_id": 27681,
        "description": "Hawkeye and his Mohican companions navigate danger during the French and Indian War. Cooper's frontier epic shaped American mythology.",
        "word_count": 145000,
        "tags": ["adventure", "historical-fiction", "classic", "public-domain"],
    },

    # === PHILOSOPHY & NON-FICTION (10 books) ===
    {
        "title": "The Republic",
        "author_name": "Plato",
        "gutenberg_id": 1497,
        "description": "Socratic dialogues on justice, the ideal state, and the nature of reality. Plato's masterwork remains foundational to Western philosophy.",
        "word_count": 115000,
        "tags": ["philosophy", "classic", "non-fiction", "public-domain"],
    },
    {
        "title": "Meditations",
        "author_name": "Marcus Aurelius",
        "gutenberg_id": 2680,
        "description": "A Roman Emperor's private reflections on Stoic philosophy and living well. Timeless wisdom on resilience, duty, and inner peace.",
        "word_count": 60000,
        "tags": ["philosophy", "stoicism", "non-fiction", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "Thus Spoke Zarathustra",
        "author_name": "Friedrich Nietzsche",
        "gutenberg_id": 1998,
        "description": "Nietzsche's philosophical novel introduces the Übermensch and eternal recurrence. Challenges conventional morality with poetic intensity.",
        "word_count": 89000,
        "tags": ["philosophy", "classic", "non-fiction", "public-domain"],
    },
    {
        "title": "The Prince",
        "author_name": "Niccolò Machiavelli",
        "gutenberg_id": 1232,
        "description": "Renaissance treatise on political power and realism. Machiavelli's controversial advice to rulers coined 'Machiavellian.'",
        "word_count": 45000,
        "tags": ["philosophy", "politics", "non-fiction", "public-domain"],
    },
    {
        "title": "Common Sense",
        "author_name": "Thomas Paine",
        "gutenberg_id": 147,
        "description": "The pamphlet that sparked American independence. Paine's plain-spoken arguments for revolution galvanized a nation.",
        "word_count": 25000,
        "tags": ["philosophy", "politics", "american-history", "public-domain"],
    },

    # === WAR & HISTORICAL FICTION (10 books) ===
    {
        "title": "The Iliad",
        "author_name": "Homer",
        "gutenberg_id": 6130,
        "description": "The epic siege of Troy and Achilles' rage. Homer's foundational work of Western literature, translated by Samuel Butler.",
        "word_count": 155000,
        "tags": ["classic", "epic", "mythology", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "The Odyssey",
        "author_name": "Homer",
        "gutenberg_id": 1727,
        "description": "Odysseus' ten-year journey home after the Trojan War. Cyclops, sirens, and gods test the cunning hero in this epic adventure.",
        "word_count": 130000,
        "tags": ["classic", "epic", "mythology", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "A Tale of Two Cities",
        "author_name": "Charles Dickens",
        "gutenberg_id": 98,
        "description": "'It was the best of times, it was the worst of times.' Dickens' masterpiece set during the French Revolution explores sacrifice and redemption.",
        "word_count": 135000,
        "tags": ["classic", "historical-fiction", "revolution", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "War and Peace",
        "author_name": "Leo Tolstoy",
        "gutenberg_id": 2600,
        "description": "Epic chronicle of Russian society during Napoleon's invasion. Tolstoy's magnum opus interweaves history, philosophy, and unforgettable characters.",
        "word_count": 587000,
        "tags": ["classic", "historical-fiction", "war", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "Les Misérables",
        "author_name": "Victor Hugo",
        "gutenberg_id": 135,
        "description": "Ex-convict Jean Valjean seeks redemption in revolutionary France. Hugo's epic of justice, love, and sacrifice inspired generations.",
        "word_count": 530000,
        "tags": ["classic", "historical-fiction", "revolution", "public-domain"],
    },

    # === AMERICAN CLASSICS (10 books) ===
    {
        "title": "Moby-Dick; or, The Whale",
        "author_name": "Herman Melville",
        "gutenberg_id": 2701,
        "description": "Captain Ahab's obsessive hunt for the white whale. Melville's epic blends adventure, philosophy, and the American spirit.",
        "word_count": 206000,
        "tags": ["classic", "adventure", "american-literature", "public-domain"],
        "is_featured": True,
    },
    {
        "title": "The Great Gatsby",
        "author_name": "F. Scott Fitzgerald",
        "gutenberg_id": 64317,
        "description": "Jazz Age glamour masks tragedy as Jay Gatsby pursues his lost love. Fitzgerald's masterpiece defines the American Dream.",
        "word_count": 47000,
        "tags": ["classic", "american-literature", "romance", "public-domain"],
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "title": "The Call of the Wild",
        "author_name": "Jack London",
        "gutenberg_id": 215,
        "description": "A domesticated dog reverts to his wild instincts during the Klondike Gold Rush. London's primal tale of survival and transformation.",
        "word_count": 32000,
        "tags": ["adventure", "classic", "animals", "public-domain"],
        "is_bestseller": True,
    },
    {
        "title": "White Fang",
        "author_name": "Jack London",
        "gutenberg_id": 910,
        "description": "A wolf-dog's journey from wilderness to civilization. London's companion to The Call of the Wild explores domestication and loyalty.",
        "word_count": 71000,
        "tags": ["adventure", "classic", "animals", "public-domain"],
    },
    {
        "title": "Little Women",
        "author_name": "Louisa May Alcott",
        "gutenberg_id": 514,
        "description": "Four sisters grow up during the Civil War. Alcott's beloved classic follows the March family with warmth, humor, and heart.",
        "word_count": 189000,
        "tags": ["classic", "family", "american-literature", "public-domain"],
        "is_bestseller": True,
    },
]
