"""Add AI-generated templates system

Revision ID: 012_ai_generated_templates
Revises: 011_add_studio_templates
Create Date: 2025-11-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, ARRAY


# revision identifiers, used by Alembic.
revision = '012_ai_generated_templates'
down_revision = '011_add_studio_templates'
branch_labels = None
depends_on = None


def upgrade():
    # Add interests field to groups table
    op.add_column('groups', sa.Column('interests', ARRAY(sa.String), nullable=True))
    
    # Create ai_generated_templates table
    op.create_table(
        'ai_generated_templates',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('slug', sa.String, nullable=False, unique=True, index=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('category', sa.String, nullable=True),  # auto-categorized by AI
        sa.Column('icon', sa.String, nullable=True),  # emoji suggested by AI
        
        # What interests triggered this template?
        sa.Column('source_interests', ARRAY(sa.String), nullable=False, index=True),
        
        # AI generation metadata
        sa.Column('ai_model', sa.String, nullable=False, default='claude-3.5-sonnet'),
        sa.Column('ai_prompt_used', sa.Text, nullable=True),  # the prompt sent to Claude
        sa.Column('generation_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        
        # Template structure (generated by AI)
        sa.Column('sections', JSONB, nullable=False),  # full section structure with prompts
        
        # Review status
        sa.Column('status', sa.String, nullable=False, default='pending', index=True),  # pending, approved, rejected, edited
        sa.Column('reviewed_by', sa.Integer, sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('review_notes', sa.Text, nullable=True),
        
        # If staff edited the template
        sa.Column('edited_sections', JSONB, nullable=True),  # Kit's improved version
        
        # Usage tracking
        sa.Column('times_suggested', sa.Integer, nullable=False, default=0),  # how many times AI suggested it
        sa.Column('times_selected', sa.Integer, nullable=False, default=0),  # how many times users picked it
        sa.Column('groups_using', sa.Integer, nullable=False, default=0),  # how many groups used it
        
        # Which group requested this template generation?
        sa.Column('requested_by_group', sa.Integer, sa.ForeignKey('groups.id', ondelete='SET NULL'), nullable=True),
        
        # If approved, convert to project_template
        sa.Column('approved_template_id', sa.Integer, sa.ForeignKey('project_templates.id', ondelete='SET NULL'), nullable=True),
        
        # Timestamps
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
    )
    
    # Index for finding approved templates by interests
    op.create_index(
        'ix_ai_templates_interests_status',
        'ai_generated_templates',
        ['source_interests', 'status']
    )
    
    # Create template_interest_mappings table (many-to-many for reusability)
    op.create_table(
        'template_interest_mappings',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('template_id', sa.Integer, sa.ForeignKey('project_templates.id', ondelete='CASCADE'), nullable=False),
        sa.Column('interest', sa.String, nullable=False, index=True),
        sa.Column('relevance_score', sa.Float, nullable=True, default=1.0),  # how relevant is this template to this interest?
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    
    # Create unique constraint on template + interest
    op.create_unique_constraint(
        'uq_template_interest',
        'template_interest_mappings',
        ['template_id', 'interest']
    )
    
    # Track AI template generations (for debugging/improving prompts)
    op.create_table(
        'ai_generation_logs',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('group_id', sa.Integer, sa.ForeignKey('groups.id', ondelete='SET NULL'), nullable=True),
        sa.Column('interests', ARRAY(sa.String), nullable=False),
        sa.Column('ai_model', sa.String, nullable=False),
        sa.Column('prompt_sent', sa.Text, nullable=False),
        sa.Column('response_received', sa.Text, nullable=True),
        sa.Column('templates_generated', sa.Integer, nullable=False, default=0),
        sa.Column('generation_time_ms', sa.Integer, nullable=True),  # how long did Claude take?
        sa.Column('error_message', sa.Text, nullable=True),
        sa.Column('success', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, index=True),
    )


def downgrade():
    op.drop_table('ai_generation_logs')
    op.drop_table('template_interest_mappings')
    op.drop_index('ix_ai_templates_interests_status', table_name='ai_generated_templates')
    op.drop_table('ai_generated_templates')
    op.drop_column('groups', 'interests')
